# Lists, arrays, dataframes

## Lists

Lists are the simplest containers that are an integral part of the Python language. A single list may contain DataTypes like Integers, Strings, as well as Objects. Lists are mutable, and hence, they can be altered even after their creation.

In [1]:
list1=[23.4, 20, True, 'Hello World']

### Accessing Lists

In [2]:
list1[0]

23.4

In [3]:
list1[3]

'Hello World'

The length of the list is given by the command len()

In [2]:
len(list1)

4

There is the typical intexation from 0 to 3 in this case. But there is also the negative indexation that goes opposite. Starting from -1 for the last list place and going downwards to -4. eg:

In [5]:
list1[-1]

'Hello World'

In [3]:
list1[-4]

23.4

### Overwritting values 

In [7]:
list1

[23.4, 20, True, 'Hello World']

In [8]:
list1[2]=5

In [9]:
list1

[23.4, 20, 5, 'Hello World']

In [10]:
list2 = [32, True, 'Hi', 56.75]

In [11]:
list1

[23.4, 20, 5, 'Hello World']

In [12]:
list2

[32, True, 'Hi', 56.75]

In [13]:
list2[3]=list1[0]

In [14]:
list2

[32, True, 'Hi', 23.4]

### List slicing

In [5]:
list3=list(range(8))

In [16]:
list3

[0, 1, 2, 3, 4, 5, 6, 7]

In [17]:
list3[:5]

[0, 1, 2, 3, 4]

In [18]:
list3[1:5]

[1, 2, 3, 4]

In [19]:
list3[3:]

[3, 4, 5, 6, 7]

In [20]:
list3[3:-2]

[3, 4, 5]

In [21]:
list4=list3[:5]

In [22]:
list4

[0, 1, 2, 3, 4]

### Slicing using steps

In [23]:
list3[1:6:2]

[1, 3, 5]

In [24]:
list3[::2]

[0, 2, 4, 6]

## Arrays

The difference from lists is that you can only have one type of variable inside. They have much more methods than the lists.

In [11]:
li=[3,5,7,8]

In [12]:
li

[3, 5, 7, 8]

In [9]:
import numpy as np

In [13]:
a = np.array(li)
#or np.array([3,5,7,8])

In [29]:
a

array([3, 5, 7, 8])

In case there are mixed variables in a list they transform to the same.

In [14]:
list1

[23.4, 20, True, 'Hello World']

In [15]:
b=np.array(list1)

In [16]:
b

array(['23.4', '20', 'True', 'Hello World'], dtype='<U32')

### Much more methods included in arrays compared to lists

In [17]:
list1.count(20)

1

In [19]:
list3

[0, 1, 2, 3, 4, 5, 6, 7]

In [20]:
c=np.array(list3)

In [21]:
c.sum()

28

### Slicing an array

When you slice an array you just take a part of it. If you change this part the initial array would be changed. To make a copy you need to run the copy command in numpy

In [22]:
c

array([0, 1, 2, 3, 4, 5, 6, 7])

In [23]:
d=c[3:5]

In [24]:
d

array([3, 4])

In [25]:
d[:]=44

In [26]:
d

array([44, 44])

In [27]:
c

array([ 0,  1,  2, 44, 44,  5,  6,  7])

In [28]:
f=c.copy()

In [29]:
f

array([ 0,  1,  2, 44, 44,  5,  6,  7])

In [30]:
f[3:5]=23

In [31]:
f

array([ 0,  1,  2, 23, 23,  5,  6,  7])

In [32]:
c

array([ 0,  1,  2, 44, 44,  5,  6,  7])

## Matrices


Using the numpy arrays we can create matrices:

In [34]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])

In [35]:
#multipling each element of one matrix with the specific element of the other
a*b

array([[4, 0],
       [0, 2]])

In [36]:
#regular matrix multiplication
np.matmul(a,b)

array([[4, 1],
       [2, 2]])

In [38]:
nparray =np.array(list(range(16)))

In [39]:
nparray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [52]:
matrix = np.reshape(nparray, (8,2) ,order='C')
# order='C' fills the lines firstly while order='F' the columns
# C stands for C programming language while F for Fortran

In [53]:
matrix

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [54]:
matrix[0,0]

0

In [55]:
matrix[7,1]

15