# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.16.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
import pandas as pd
df = pd.read_csv('diabetes.csv')
df.head() #View first rows

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [5]:
X = df.iloc[:,0:8]
y = df.iloc[:,8]

In [6]:
print(X)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  


In [7]:
print(y)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64


### Splitting the dataset into the Training set and Test set

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

### Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [10]:
from keras.models import Sequential
from keras.layers import Dense, Input

In [11]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [12]:
ann.add(Input(shape=(8,)))  # This is the Input layer

In [13]:
ann.add(tf.keras.layers.Dense(12, activation='relu'))

### Adding the second hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(8, activation='relu'))

### Adding the output layer

In [15]:
#for non-binary classification activation='softmax'
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [16]:
#for non-binary classification loss ='categorical_crossentropy'
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [17]:
ann.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 12)             │           108 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │           104 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 221 (884.00 B)

 Trainable params: 221 (884.00 B)

 Non-trainable params: 0 (0.00 B)

### Training the ANN on the Training set

In [18]:
ann.fit(X_train, y_train, batch_size = 10, epochs = 150)

Epoch 1/150
62/62 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.4259 - loss: 0.7285
Epoch 2/150
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6011 - loss: 0.6689
Epoch 3/150
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7333 - loss: 0.6187
Epoch 4/150
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7308 - loss: 0.5954
Epoch 5/150
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7710 - loss: 0.5543
Epoch 6/150
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7621 - loss: 0.5270
Epoch 7/150
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.4930
Epoch 8/150
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.5024
Epoch 9/150
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4765
Epoch 10/150
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7879 - loss: 0.4614
Epoch 11/150
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7972 - loss: 0.4631
Epoch 12/150
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy:

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [19]:
y_pred = ann.predict(X_test)
y_pred

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


array([[6.01257198e-03],
       [8.62467468e-01],
       [8.79754424e-01],
       [9.45105076e-01],
       [2.13867202e-01],
       [2.86339253e-01],
       [7.51182530e-03],
       [5.44660091e-02],
       [4.75418329e-01],
       [5.09255052e-01],
       [7.26761147e-02],
       [7.33582020e-01],
       [1.46722615e-01],
       [2.05521822e-01],
       [3.10891075e-03],
       [9.82896890e-03],
       [1.75697938e-01],
       [2.40837499e-01],
       [2.10779086e-01],
       [1.00776404e-01],
       [5.21107763e-02],
       [1.09754037e-02],
       [4.61031973e-01],
       [8.99953902e-01],
       [6.88705519e-02],
       [1.08404711e-01],
       [1.93692684e-01],
       [6.42425776e-01],
       [2.06502333e-01],
       [1.45678133e-01],
       [2.24624366e-01],
       [2.17810109e-01],
       [1.09897880e-02],
       [1.39106244e-01],
       [2.45019998e-02],
       [9.60466862e-01],
       [1.39182732e-01],
       [1.77608326e-01],
       [8.24990720e-02],
       [1.47904232e-01],


In [20]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [

In [21]:
y_test

348    0
424    1
546    1
235    1
451    1
      ..
217    0
246    0
1      0
134    0
553    0
Name: Outcome, Length: 154, dtype: int64

### Making the Confusion Matrix

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[86 17]
 [19 32]]


0.7662337662337663

In [23]:
# Evaluate the model on test data
loss, accuracy = ann.evaluate(X_test, y_test)
print(f'Test loss: {loss}')
print(f'Test accuracy: {accuracy}')

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7732 - loss: 0.4754  
Test loss: 0.4656040072441101
Test accuracy: 0.7662337422370911
